---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    mas_installed_app_ids:
      - 497799835 # Xcode

    homebrew_installed_packages:
      - nvm
      - pyenv
      - pipenv
      - goenv
      - git
      - zsh

    homebrew_cask_apps:
      - docker
      - iterm2
      - google-chrome
      - visual-studio-code

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas